sudo: false
branches:
  only:
    - /master.*/
    - /develop.*/
    - /feature\/.*/
language: cpp
script:
  - pushd src/engine
  - ./build.sh
  - popd
  - ./bootstrap.sh --with-toolset=${TOOLSET}
  - pushd test
  - python test_all.py ${TOOLSET}
  - popd
stages:
  - name: test
  - name: website update
    if: branch IN (develop,master) AND type IN (push)
jobs:
  include:
    - os: linux
      dist: trusty
      env: TOOLSET=gcc
    - os: linux
      dist: trusty
      env: TOOLSET=clang
    - os: linux
      dist: precise
      env: TOOLSET=gcc
    - os: linux
      dist: precise
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode10
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode9.4
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode9.3
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode9.2
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode9.1
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode9
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode8.3
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode8
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode7.3
      env: TOOLSET=clang
    - stage: website update
      os: linux
      script:
        - gem install asciidoctor
        - gem install pygments.rb
        - pip install --user Pygments
        - pip install --user https://github.com/bfgroup/jam_pygments/archive/master.zip
        - git config user.email "b2-bot"
        - git config user.name "b2-bot"
        - echo "using asciidoctor ;" >> project-config.jam
        - pushd src/engine
        - ./build.sh
        - popd
        - ./bootstrap.sh --with-toolset=${TOOLSET}
        - pushd doc
        - ../b2 --website-doc-dir=manual/${TRAVIS_BRANCH} website
